apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql-cluster.fullname" . }}-admin-configuration
  labels:
    {{- include "proxysql-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  proxysql-admin.cnf: |-
    # proxysql admin interface credentials.
    export PROXYSQL_DATADIR='/opt/proxysql-admin-tool/var'
    export PROXYSQL_USERNAME={{ .Values.database.accounts.admin.username | squote }}
    export PROXYSQL_PASSWORD={{ .Values.database.accounts.admin.password | squote }}
    export PROXYSQL_HOSTNAME={{ printf "%s-leader" (include "proxysql-cluster.fullname" .) | squote }}
    export PROXYSQL_PORT={{ .Values.tcpPort.proxysqlAdmin | squote }}

    # PXC admin credentials for connecting to the pxc-cluster-nodes.
    export CLUSTER_USERNAME={{ .Values.database.accounts.root.username | squote }}
    export CLUSTER_PASSWORD={{ .Values.database.accounts.root.password | squote }}
    export CLUSTER_HOSTNAME={{ .Values.database.servers | first | squote }}
    export CLUSTER_PORT={{ .Values.tcpPort.databaseCluster | squote }}

    # proxysql monitoring user. the proxysql admin script will create this user
    # in pxc to monitor pxc-nodes.
    export MONITOR_USERNAME={{ .Values.database.accounts.monitor.username | squote }}
    export MONITOR_PASSWORD={{ .Values.database.accounts.monitor.password | squote }}

    # Application user to connect to pxc-node through proxysql
    #export CLUSTER_APP_USERNAME=''
    #export CLUSTER_APP_PASSWORD=''

    # ProxySQL read/write hostgroup
    export WRITE_HOSTGROUP_ID='10'
    export READ_HOSTGROUP_ID='20'

    # ProxySQL read/write configuration mode.
    export MODE='singlewrite'
