apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql-cluster.fullname" . }}-follower
spec:
  selector:
    {{- include "proxysql-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: follower
  ports:
  - protocol: TCP
    port: {{ .Values.tcpPort.proxysqlCluster }}
    targetPort: {{ .Values.tcpPort.proxysqlCluster }}
    name: proxysql
  - protocol: TCP
    port: {{ .Values.tcpPort.proxysqlAdmin }}
    targetPort: {{ .Values.tcpPort.proxysqlAdmin }}
    name: proxysql-admin
