apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxysql-cluster.fullname" . }}-follower
  labels:
    {{- include "proxysql-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: follower
spec:
  replicas: {{ .Values.replicaCount.follower }}
  selector:
    matchLabels:
      {{- include "proxysql-cluster.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: follower
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "proxysql-cluster.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: follower
    spec:
      serviceAccountName: {{ include "proxysql-cluster.serviceAccountName" . }}
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: proxysql
          volumeMounts:
          - name: proxysql-follower-config
            mountPath: /etc/proxysql.cnf
            subPath: proxysql.cnf
          ports:
          - containerPort: {{ .Values.tcpPort.proxysqlCluster }}
            name: proxysql-mysql
          - containerPort: {{ .Values.tcpPort.proxysqlAdmin }}
            name: proxysql-admin
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: proxysql-follower-config
          secret:
            secretName: {{ include "proxysql-cluster.fullname" . }}-follower-configuration
