apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql-cluster.fullname" . }}-leader-configuration
  labels:
    {{- include "proxysql-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  proxysql.cnf: |-
    datadir = "/var/lib/proxysql"
    admin_variables = {
      admin_credentials = "
        {{- .Values.database.accounts.admin.username -}}
      :
        {{- .Values.database.accounts.admin.password -}}
      "
      mysql_ifaces = "0.0.0.0:{{ .Values.tcpPort.proxysqlAdmin }}"
      refresh_interval = 2000
      cluster_username = {{ .Values.database.accounts.admin.username | quote }}
      cluster_password = {{ .Values.database.accounts.admin.password | quote }}
    }
    mysql_variables = {
      threads = 4
      max_connections = 2048
      default_query_delay = 0
      default_query_timeout = 36000000
      have_compress = true
      poll_timeout = 2000
      interfaces = "0.0.0.0:{{ .Values.tcpPort.proxysqlCluster }};/tmp/proxysql.sock"
      default_schema = "information_schema"
      stacksize = 1048576
      server_version = "5.1.30"
      connect_timeout_server = 10000
      monitor_history = 60000
      monitor_connect_interval = 200000
      monitor_ping_interval = 200000
      ping_interval_server_msec = 10000
      ping_timeout_server = 200
      commands_stats = true
      sessions_sort = true
      monitor_username = {{ .Values.database.accounts.monitor.username | quote }}
      monitor_password = {{ .Values.database.accounts.monitor.password | quote }}
    }
    mysql_replication_hostgroups = (
      {
        writer_hostgroup = 10,
        reader_hostgroup = 20,
        comment = "MySQL Replication 5.7"
      }
    )
    mysql_servers = (
      {{- range .Values.database.servers }}
      {
        address = {{ . | quote }},
        port = {{ $.Values.tcpPort.databaseCluster | quote }},
        hostgroup = 10,
        max_connections = 100
      },
      {
        address = {{ . | quote }},
        port = {{ $.Values.tcpPort.databaseCluster | quote }},
        hostgroup = 20,
        max_connections = 100
      },
      {{- end }}
    )
    mysql_users = ( )
    mysql_query_rules = (
      {
        rule_id = 100
        active = 1
        match_pattern = "^SELECT .* FOR UPDATE"
        destination_hostgroup = 10
        apply = 1
      },
      {
        rule_id = 200
        active = 1
        match_pattern = "^SELECT .*"
        destination_hostgroup = 20
        apply = 1
      },
      {
        rule_id = 300
        active = 1
        match_pattern = ".*"
        destination_hostgroup = 10
        apply = 1
      }
    )
