apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql-cluster.fullname" . }}-follower-configuration
  labels:
    {{- include "proxysql-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  proxysql.cnf: |-
    datadir = "/var/lib/proxysql"
    admin_variables = {
      admin_credentials = "
        {{- .Values.database.accounts.admin.username -}}
      :
        {{- .Values.database.accounts.admin.password -}}
      "
      mysql_ifaces = "0.0.0.0:{{ .Values.tcpPort.proxysqlAdmin }}"
      refresh_interval = 2000
      cluster_username = "{{ .Values.database.accounts.admin.username }}"
      cluster_password = "{{ .Values.database.accounts.admin.password }}"
      cluster_proxysql_servers_diffs_before_sync = 0
    }
    mysql_variables = {
      threads = 4
      max_connections = 2048
      default_query_delay = 0
      default_query_timeout = 36000000
      have_compress = true
      poll_timeout = 2000
      interfaces = "0.0.0.0:{{ .Values.tcpPort.proxysqlCluster }};/tmp/proxysql.sock"
      default_schema = "information_schema"
      stacksize = 1048576
      server_version = "5.1.30"
      connect_timeout_server = 10000
      monitor_history = 60000
      monitor_connect_interval = 200000
      monitor_ping_interval = 200000
      ping_interval_server_msec = 10000
      ping_timeout_server = 200
      commands_stats = true
      sessions_sort = true
      monitor_username = {{ .Values.database.accounts.monitor.username | quote }}
      monitor_password = {{ .Values.database.accounts.monitor.password | quote }}
    }
    proxysql_servers = (
      {
        hostname={{ printf "%s-leader" (include "proxysql-cluster.fullname" .) | quote }}
        port={{ .Values.tcpPort.proxysqlAdmin }}
        weight=0
      }
    )

