apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql-cluster.fullname" . }}-my-cnf
  labels:
    {{- include "proxysql-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  .my.cnf: |-
    [client]
    host={{ printf "%s-leader" (include "proxysql-cluster.fullname" .) | quote }}
    port={{ .Values.tcpPort.proxysqlAdmin | quote }}
    user={{ .Values.database.accounts.admin.username | quote }}
    password={{ .Values.database.accounts.admin.password | quote }}
